CREATE TABLE BALL_RED_BASE (
    RED_1   NUMBER(2,0) NOT NULL,
    RED_2   NUMBER(2,0) NOT NULL,
    RED_3   NUMBER(2,0) NOT NULL,
    RED_4   NUMBER(2,0) NOT NULL,
    RED_5   NUMBER(2,0) NOT NULL,
    RED_6   NUMBER(2,0) NOT NULL
);

CREATE TABLE BALL_RED_FILTER (
    RED_1        NUMBER(2,0) NOT NULL,
    RED_2        NUMBER(2,0) NOT NULL,
    RED_3        NUMBER(2,0) NOT NULL,
    RED_4        NUMBER(2,0) NOT NULL,
    RED_5        NUMBER(2,0) NOT NULL,
    RED_6        NUMBER(2,0) NOT NULL,
    INTERVAL_3   CHAR(3),
    INTERVAL_4   CHAR(4)
);

CREATE TABLE BALL_HISTORY (
    RED_1        NUMBER(2,0) NOT NULL,
    RED_2        NUMBER(2,0) NOT NULL,
    RED_3        NUMBER(2,0) NOT NULL,
    RED_4        NUMBER(2,0) NOT NULL,
    RED_5        NUMBER(2,0) NOT NULL,
    RED_6        NUMBER(2,0) NOT NULL,
    BLUE         NUMBER(2,0) NOT NULL,
    INTERVAL_3   CHAR(3),
    INTERVAL_4   CHAR(4),
    DATE_NO      NUMBER(7,0) NOT NULL,
    CONSTRAINT BALL_HISTORY_PK PRIMARY KEY ( DATE_NO )
);